### ISSUE TITLE
Enable scrolling on peer list

### ISSUE THREAD

**Issue by der-eismann** [maxgallup/tailscale-status#21]
Hey, thanks for this cool extension! Unfortunately there is an issue for me as we use tailscale in our company with lots of devices in our tailnet. When I click the extension icon, all I see are the connected and disconnected devices, the other options are hidden "below my screen". Would be cool if someone could add the ability to scroll the list, or set a maximum of x devices so you can still see the other menu points.

**Comment by matdave** [comment]
I believe pull request number #19 partially solves this, but it would be good to have a scroll effect on the subsequent node list.

**Comment by maxgallup** [comment]
The extension should be updated with #19 merged soon and should provide scrolling now.

I will close this issue but reopen another one, since ideally for less than say 7 nodes, there would be no drop down list to quickly view all of the nodes at once. When time frees up I will look into this solution more.
